name: Docker Image Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag nodeimage:$(date +%s)
    - name: Trivy Scan
    - uses: homoluctus/gitrivy@v2.0.0
  
      with:
        image: nodeimage:$(date +%s)
         
