name: Docker Image Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout code
      
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag nodeimage:1
  
    - uses: homoluctus/gitrivy@v2.0.0
      name: Trivy Scan
      with:
        image: nodeimage:1
    
    - name: Trivy Scan using authentic scanner
      run: |
       docker pull aquasec/trivy
       docker run --rm aquasec/trivy nodeimage:1    
